services:
  # PostgreSQL - Development Database
  postgres-dev:
    image: postgres:15-alpine
    container_name: quillspace-postgres-dev
    environment:
      POSTGRES_DB: quillspace_dev
      POSTGRES_USER: quillspace
      POSTGRES_PASSWORD: dev_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quillspace -d quillspace_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ClickHouse - Development Analytics Database
  clickhouse-dev:
    image: clickhouse/clickhouse-server:23-alpine
    container_name: quillspace-clickhouse-dev
    environment:
      CLICKHOUSE_DB: analytics_dev
      CLICKHOUSE_USER: quillspace
      CLICKHOUSE_PASSWORD: dev_password
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse_dev_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  clickhouse_dev_data:
    driver: local
