version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: quillspace-postgres
    environment:
      POSTGRES_DB: quillspace_dev
      POSTGRES_USER: quillspace
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./quillspace-core/migrations:/docker-entrypoint-initdb.d
      - ./scripts:/docker-entrypoint-initdb.d/scripts
    command: ["postgres", "-c", "log_statement=none"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quillspace -d quillspace_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - quillspace

  # ClickHouse Analytics Database
  clickhouse:
    image: clickhouse/clickhouse-server:23-alpine
    container_name: quillspace-clickhouse
    environment:
      CLICKHOUSE_DB: analytics_dev
      CLICKHOUSE_USER: quillspace
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-dev_password}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - quillspace

  # Rust Backend
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: quillspace-backend
    environment:
      - RUN_MODE=development
      - RUST_LOG=info
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_password}
      - QUILLSPACE__DATABASE__URL=postgresql://quillspace:${POSTGRES_PASSWORD:-dev_password}@postgres:5432/quillspace_dev
      - QUILLSPACE__CLICKHOUSE__URL=http://clickhouse:8123
      - QUILLSPACE__CLICKHOUSE__USERNAME=quillspace
      - QUILLSPACE__CLICKHOUSE__PASSWORD=${CLICKHOUSE_PASSWORD:-dev_password}
      - QUILLSPACE__CLICKHOUSE__DATABASE=analytics_dev
      - QUILLSPACE__SERVER__HOST=0.0.0.0
      - QUILLSPACE__AUTH__JWT_SECRET=${JWT_SECRET:-your-super-secure-jwt-secret-key-that-is-at-least-32-characters-long-change-in-production}
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - quillspace
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Qwik Frontend
  frontend:
    build:
      context: ./quillspace-client
      dockerfile: Dockerfile
    container_name: quillspace-frontend
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3001/api}
      - VITE_INTERNAL_API_URL=http://backend:3000/api
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - quillspace
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: quillspace-redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-dev_password} --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - quillspace

volumes:
  postgres_data:
    driver: local
  clickhouse_data:
    driver: local
  redis_data:
    driver: local

networks:
  quillspace:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
