["component.quillspace-core"]
template = "server"
framework = "axum"
created_at = "2025-10-04T18:43:49.244369-06:00"

["component.quilspace-lib"]
template = "library"
created_at = "2025-10-04T18:44:15.948200-06:00"
