[server]
host = "127.0.0.1"
port = 3000

[database]
url = "postgresql://quillspace:dev_password@localhost:5432/quillspace_dev"
max_connections = 5
min_connections = 1

[clickhouse]
url = "http://localhost:8123"
database = "analytics_dev"
username = "quillspace"
password = "dev_password"
compression = "lz4"

[auth]
jwt_secret = "dev-secret-key-that-is-at-least-32-characters-long-not-for-production"
jwt_expiration = 7200  # 2 hours for development

[observability]
metrics_enabled = true
tracing_enabled = true
prometheus_port = 9091
