apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-dev:9090
    isDefault: true
    
  - name: ClickHouse
    type: clickhouse
    access: proxy
    url: http://clickhouse-dev:8123
    database: analytics_dev
    user: quillspace
    password: dev_password
